package com.tienda.a_shop.dao.interfaces;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.tienda.a_shop.entities.Categoria;
import com.tienda.a_shop.entities.Item;
import com.tienda.a_shop.entities.CategoriaXGastoMes;
import com.tienda.a_shop.entities.GastoMes;

import com.tienda.a_shop.dao.interfaces.CategoriaDao;
import com.tienda.a_shop.dao.interfaces.ItemDao;
import com.tienda.a_shop.dao.interfaces.CategoriaXGastoMesDao;
import com.tienda.a_shop.dao.interfaces.GastoMesDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig categoriaDaoConfig;
    private final DaoConfig itemDaoConfig;
    private final DaoConfig categoriaXGastoMesDaoConfig;
    private final DaoConfig gastoMesDaoConfig;

    private final CategoriaDao categoriaDao;
    private final ItemDao itemDao;
    private final CategoriaXGastoMesDao categoriaXGastoMesDao;
    private final GastoMesDao gastoMesDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        categoriaDaoConfig = daoConfigMap.get(CategoriaDao.class).clone();
        categoriaDaoConfig.initIdentityScope(type);

        itemDaoConfig = daoConfigMap.get(ItemDao.class).clone();
        itemDaoConfig.initIdentityScope(type);

        categoriaXGastoMesDaoConfig = daoConfigMap.get(CategoriaXGastoMesDao.class).clone();
        categoriaXGastoMesDaoConfig.initIdentityScope(type);

        gastoMesDaoConfig = daoConfigMap.get(GastoMesDao.class).clone();
        gastoMesDaoConfig.initIdentityScope(type);

        categoriaDao = new CategoriaDao(categoriaDaoConfig, this);
        itemDao = new ItemDao(itemDaoConfig, this);
        categoriaXGastoMesDao = new CategoriaXGastoMesDao(categoriaXGastoMesDaoConfig, this);
        gastoMesDao = new GastoMesDao(gastoMesDaoConfig, this);

        registerDao(Categoria.class, categoriaDao);
        registerDao(Item.class, itemDao);
        registerDao(CategoriaXGastoMes.class, categoriaXGastoMesDao);
        registerDao(GastoMes.class, gastoMesDao);
    }
    
    public void clear() {
        categoriaDaoConfig.clearIdentityScope();
        itemDaoConfig.clearIdentityScope();
        categoriaXGastoMesDaoConfig.clearIdentityScope();
        gastoMesDaoConfig.clearIdentityScope();
    }

    public CategoriaDao getCategoriaDao() {
        return categoriaDao;
    }

    public ItemDao getItemDao() {
        return itemDao;
    }

    public CategoriaXGastoMesDao getCategoriaXGastoMesDao() {
        return categoriaXGastoMesDao;
    }

    public GastoMesDao getGastoMesDao() {
        return gastoMesDao;
    }

}
